# Generated by Django 4.2.2 on 2026-07-17 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("executando", "Executando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("percentual", models.PositiveSmallIntegerField(default=0)),
                ("mensagem", models.CharField(blank=True, default="", max_length=500)),
                (
                    "nivel_mensagem",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("info", "Info"),
                            ("error", "Erro"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "template_resultado",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("contexto_extra", models.JSONField(blank=True, default=dict)),
                ("resultado_html", models.TextField(blank=True, default="")),
                (
                    "redirect_url",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("erro_detalhe", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-criado_em"],},
        ),
    ]
