# Generated by Django 4.1.7 on 2023-04-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0002_remove_cargahoraria_ano_remove_cargahoraria_mes"),
        ("relatorios", "0002_relatoriosolicitacao_importacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatorionegativos",
            name="importacao",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="empregados.importacoes",
            ),
            preserve_default=False,
        ),
    ]
