# Generated by Django 4.1.7 on 2023-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0004_relatorioerros_importacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatorionegativos",
            name="tipo",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
