# Generated by Django 4.1.7 on 2023-04-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0005_relatorionegativos_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatoriopagas",
            name="qtd",
            field=models.IntegerField(default=1),
        ),
    ]
