# Generated by Django 4.1.7 on 2023-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0006_alter_relatoriopagas_qtd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatoriocodigo90",
            name="cod_afastamento",
            field=models.IntegerField(default=90),
        ),
    ]
