# Generated by Django 4.1.7 on 2023-04-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0002_remove_cargahoraria_ano_remove_cargahoraria_mes"),
        ("relatorios", "0007_alter_relatoriocodigo90_cod_afastamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriocodigo90",
            name="importacao",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="empregados.importacoes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatorioconfirmacao",
            name="importacao",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="empregados.importacoes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatorioentradasaida",
            name="importacao",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="empregados.importacoes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatoriopagas",
            name="importacao",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="empregados.importacoes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatoriorejeitarbatidas",
            name="importacao",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="empregados.importacoes",
            ),
            preserve_default=False,
        ),
    ]
