# Generated by Django 4.1.7 on 2023-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0008_relatoriocodigo90_importacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriopagas",
            name="setor",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
