# Generated by Django 4.1.7 on 2023-05-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0004_alter_cargahoraria_nome_alter_empregado_nome"),
        ("relatorios", "0010_alter_relatorioconfirmacao_dia1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoltarNegativos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("dia1", models.CharField(max_length=30, null=True)),
                ("dia2", models.CharField(max_length=30, null=True)),
                ("dia3", models.CharField(max_length=30, null=True)),
                ("dia4", models.CharField(max_length=30, null=True)),
                ("dia5", models.CharField(max_length=30, null=True)),
                ("dia6", models.CharField(max_length=30, null=True)),
                ("dia7", models.CharField(max_length=30, null=True)),
                ("dia8", models.CharField(max_length=30, null=True)),
                ("dia9", models.CharField(max_length=30, null=True)),
                ("dia10", models.CharField(max_length=30, null=True)),
                ("dia11", models.CharField(max_length=30, null=True)),
                ("dia12", models.CharField(max_length=30, null=True)),
                ("dia13", models.CharField(max_length=30, null=True)),
                ("dia14", models.CharField(max_length=30, null=True)),
                ("dia15", models.CharField(max_length=30, null=True)),
                ("dia16", models.CharField(max_length=30, null=True)),
                ("dia17", models.CharField(max_length=30, null=True)),
                ("dia18", models.CharField(max_length=30, null=True)),
                ("dia19", models.CharField(max_length=30, null=True)),
                ("dia20", models.CharField(max_length=30, null=True)),
                ("dia21", models.CharField(max_length=30, null=True)),
                ("dia22", models.CharField(max_length=30, null=True)),
                ("dia23", models.CharField(max_length=30, null=True)),
                ("dia24", models.CharField(max_length=30, null=True)),
                ("dia25", models.CharField(max_length=30, null=True)),
                ("dia26", models.CharField(max_length=30, null=True)),
                ("dia27", models.CharField(max_length=30, null=True)),
                ("dia28", models.CharField(max_length=30, null=True)),
                ("dia29", models.CharField(max_length=30, null=True)),
                ("dia30", models.CharField(max_length=30, null=True)),
                ("dia31", models.CharField(max_length=30, null=True)),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                ("data_upload", models.DateTimeField()),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
    ]
