# Generated by Django 4.1.7 on 2023-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0011_voltarnegativos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorioconfirmacao",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="relatorioentradasaida",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="relatorioerros",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="relatorionegativos",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="relatoriopagas",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="relatoriorejeitarbatidas",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="relatoriosolicitacao",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="voltarnegativos",
            name="nome",
            field=models.CharField(max_length=150),
        ),
    ]
