# Generated by Django 4.2.2 on 2024-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0013_alter_relatorioconfirmacao_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorioconfirmacao",
            name="setor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="relatorioentradasaida",
            name="setor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="relatorionegativos",
            name="setor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="relatoriopagas",
            name="setor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="relatoriosolicitacao",
            name="setor",
            field=models.CharField(max_length=200),
        ),
    ]
