# Generated by Django 4.2.2 on 2024-04-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0016_alter_relatorioconfirmacao_dia1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatorioerros",
            options={
                "ordering": [
                    "nome",
                    "data",
                    "escala",
                    "entrada",
                    "saida",
                    "horas_diurnas",
                    "horas_noturnas",
                    "horas_trabalhadas",
                    "importado_por",
                    "importado_por_id",
                    "data_upload",
                    "tipo",
                    "setor",
                ]
            },
        ),
        migrations.AddField(
            model_name="relatoriocodigo90",
            name="setor",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatorioerros",
            name="setor",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatoriorejeitarbatidas",
            name="setor",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voltarnegativos",
            name="setor",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
