# Generated by Django 4.2.2 on 2024-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "relatorios",
            "0019_alter_relatorioerros_options_relatoriocodigo90_setor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorioerros",
            name="entrada",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="relatorioerros",
            name="saida",
            field=models.CharField(max_length=100),
        ),
    ]
