# Generated by Django 4.1.7 on 2023-04-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empregados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("dia1", models.CharField(max_length=5)),
                ("dia2", models.CharField(max_length=5)),
                ("dia3", models.CharField(max_length=5)),
                ("dia4", models.CharField(max_length=5)),
                ("dia5", models.CharField(max_length=5)),
                ("dia6", models.CharField(max_length=5)),
                ("dia7", models.CharField(max_length=5)),
                ("dia8", models.CharField(max_length=5)),
                ("dia9", models.CharField(max_length=5)),
                ("dia10", models.CharField(max_length=5)),
                ("dia11", models.CharField(max_length=5)),
                ("dia12", models.CharField(max_length=5)),
                ("dia13", models.CharField(max_length=5)),
                ("dia14", models.CharField(max_length=5)),
                ("dia15", models.CharField(max_length=5)),
                ("dia16", models.CharField(max_length=5)),
                ("dia17", models.CharField(max_length=5)),
                ("dia18", models.CharField(max_length=5)),
                ("dia19", models.CharField(max_length=5)),
                ("dia20", models.CharField(max_length=5)),
                ("dia21", models.CharField(max_length=5)),
                ("dia22", models.CharField(max_length=5)),
                ("dia23", models.CharField(max_length=5)),
                ("dia24", models.CharField(max_length=5)),
                ("dia25", models.CharField(max_length=5)),
                ("dia26", models.CharField(max_length=5)),
                ("dia27", models.CharField(max_length=5)),
                ("dia28", models.CharField(max_length=5)),
                ("dia29", models.CharField(max_length=5)),
                ("dia30", models.CharField(max_length=5)),
                ("dia31", models.CharField(max_length=5)),
                ("data_upload", models.DateTimeField()),
                ("mes", models.CharField(max_length=15)),
                ("ano", models.IntegerField()),
                ("setor", models.CharField(max_length=100)),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("batida1", models.TimeField()),
                ("batida2", models.TimeField()),
                ("batida3", models.TimeField()),
                ("batida4", models.TimeField()),
                ("batida5", models.TimeField()),
                ("batida6", models.TimeField()),
                ("escala", models.CharField(max_length=100)),
                ("mes", models.CharField(max_length=15)),
                ("ano", models.IntegerField()),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Confirmacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("dia1", models.CharField(max_length=5)),
                ("dia2", models.CharField(max_length=5)),
                ("dia3", models.CharField(max_length=5)),
                ("dia4", models.CharField(max_length=5)),
                ("dia5", models.CharField(max_length=5)),
                ("dia6", models.CharField(max_length=5)),
                ("dia7", models.CharField(max_length=5)),
                ("dia8", models.CharField(max_length=5)),
                ("dia9", models.CharField(max_length=5)),
                ("dia10", models.CharField(max_length=5)),
                ("dia11", models.CharField(max_length=5)),
                ("dia12", models.CharField(max_length=5)),
                ("dia13", models.CharField(max_length=5)),
                ("dia14", models.CharField(max_length=5)),
                ("dia15", models.CharField(max_length=5)),
                ("dia16", models.CharField(max_length=5)),
                ("dia17", models.CharField(max_length=5)),
                ("dia18", models.CharField(max_length=5)),
                ("dia19", models.CharField(max_length=5)),
                ("dia20", models.CharField(max_length=5)),
                ("dia21", models.CharField(max_length=5)),
                ("dia22", models.CharField(max_length=5)),
                ("dia23", models.CharField(max_length=5)),
                ("dia24", models.CharField(max_length=5)),
                ("dia25", models.CharField(max_length=5)),
                ("dia26", models.CharField(max_length=5)),
                ("dia27", models.CharField(max_length=5)),
                ("dia28", models.CharField(max_length=5)),
                ("dia29", models.CharField(max_length=5)),
                ("dia30", models.CharField(max_length=5)),
                ("dia31", models.CharField(max_length=5)),
                ("data_upload", models.DateTimeField()),
                ("mes", models.CharField(max_length=15)),
                ("ano", models.IntegerField()),
                ("setor", models.CharField(max_length=100)),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BancoTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("saldo", models.CharField(max_length=20)),
                ("saldo_decimal", models.FloatField()),
                ("data_upload", models.DateTimeField()),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                ("mes", models.CharField(max_length=15)),
                ("ano", models.IntegerField()),
                ("tipo", models.CharField(max_length=20)),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BancoMes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("saldo", models.CharField(max_length=20)),
                ("saldo_decimal", models.FloatField()),
                ("data_upload", models.DateTimeField()),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                ("mes", models.CharField(max_length=15)),
                ("ano", models.IntegerField()),
                ("momento", models.CharField(max_length=30)),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
    ]
