# Generated by Django 4.1.7 on 2023-04-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("horas_extras", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bancomes", name="ano",),
        migrations.RemoveField(model_name="bancomes", name="mes",),
        migrations.RemoveField(model_name="bancototal", name="ano",),
        migrations.RemoveField(model_name="bancototal", name="mes",),
        migrations.RemoveField(model_name="confirmacao", name="ano",),
        migrations.RemoveField(model_name="confirmacao", name="mes",),
        migrations.RemoveField(model_name="frequencia", name="ano",),
        migrations.RemoveField(model_name="frequencia", name="mes",),
        migrations.RemoveField(model_name="solicitacao", name="ano",),
        migrations.RemoveField(model_name="solicitacao", name="mes",),
    ]
