# Generated by Django 4.1.7 on 2023-04-05 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "horas_extras",
            "0003_remove_bancomes_momento_remove_bancototal_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="frequencia",
            name="data_upload",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 5, 11, 33, 8, 794620)
            ),
        ),
    ]
