# Generated by Django 4.1.7 on 2023-04-14 10:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "horas_extras",
            "0016_alter_confirmacao_dia1_alter_confirmacao_dia10_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="frequencia",
            name="data_upload",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 14, 10, 46, 58, 364589)
            ),
        ),
    ]
