# Generated by Django 4.1.7 on 2023-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horas_extras", "0025_alter_solicitacao_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancomes", name="nome", field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="bancototal",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="nome",
            field=models.CharField(max_length=150),
        ),
    ]
