# Generated by Django 4.1.7 on 2023-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horas_extras", "0026_alter_bancomes_nome_alter_bancototal_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bancomes", name="nome", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bancototal",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="confirmacao",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="nome",
            field=models.CharField(max_length=200),
        ),
    ]
