# Generated by Django 4.2.2 on 2024-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horas_extras", "0027_alter_bancomes_nome_alter_bancototal_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmacao",
            name="setor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="setor",
            field=models.CharField(max_length=200),
        ),
    ]
