# Generated by Django 4.1.7 on 2023-04-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cargahoraria", name="ano",),
        migrations.RemoveField(model_name="cargahoraria", name="mes",),
    ]
