# Generated by Django 4.1.7 on 2023-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0002_remove_cargahoraria_ano_remove_cargahoraria_mes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empregado", name="mes", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="importacoes", name="mes", field=models.IntegerField(),
        ),
    ]
