# Generated by Django 4.1.7 on 2023-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0003_alter_empregado_mes_alter_importacoes_mes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargahoraria",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="empregado", name="nome", field=models.CharField(max_length=150),
        ),
    ]
