# Generated by Django 4.1.7 on 2023-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0004_alter_cargahoraria_nome_alter_empregado_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargahoraria",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="empregado", name="nome", field=models.CharField(max_length=200),
        ),
    ]
