# Generated by Django 4.2.2 on 2023-06-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empregados", "0005_alter_cargahoraria_nome_alter_empregado_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanilhaSolicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=100)),
                ("dia1", models.CharField(max_length=10)),
                ("dia2", models.CharField(max_length=10)),
                ("dia3", models.CharField(max_length=10)),
                ("dia4", models.CharField(max_length=10)),
                ("dia5", models.CharField(max_length=10)),
                ("dia6", models.CharField(max_length=10)),
                ("dia7", models.CharField(max_length=10)),
                ("dia8", models.CharField(max_length=10)),
                ("dia9", models.CharField(max_length=10)),
                ("dia10", models.CharField(max_length=10)),
                ("dia11", models.CharField(max_length=10)),
                ("dia12", models.CharField(max_length=10)),
                ("dia13", models.CharField(max_length=10)),
                ("dia14", models.CharField(max_length=10)),
                ("dia15", models.CharField(max_length=10)),
                ("dia16", models.CharField(max_length=10)),
                ("dia17", models.CharField(max_length=10)),
                ("dia18", models.CharField(max_length=10)),
                ("dia19", models.CharField(max_length=10)),
                ("dia20", models.CharField(max_length=10)),
                ("dia21", models.CharField(max_length=10)),
                ("dia22", models.CharField(max_length=10)),
                ("dia23", models.CharField(max_length=10)),
                ("dia24", models.CharField(max_length=10)),
                ("dia25", models.CharField(max_length=10)),
                ("dia26", models.CharField(max_length=10)),
                ("dia27", models.CharField(max_length=10)),
                ("dia28", models.CharField(max_length=10)),
                ("dia29", models.CharField(max_length=10)),
                ("dia30", models.CharField(max_length=10)),
                ("dia31", models.CharField(max_length=10)),
                ("data_upload", models.DateTimeField()),
                ("setor", models.CharField(max_length=100)),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanilhaConfirmacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=100)),
                ("dia1", models.CharField(max_length=10)),
                ("dia2", models.CharField(max_length=10)),
                ("dia3", models.CharField(max_length=10)),
                ("dia4", models.CharField(max_length=10)),
                ("dia5", models.CharField(max_length=10)),
                ("dia6", models.CharField(max_length=10)),
                ("dia7", models.CharField(max_length=10)),
                ("dia8", models.CharField(max_length=10)),
                ("dia9", models.CharField(max_length=10)),
                ("dia10", models.CharField(max_length=10)),
                ("dia11", models.CharField(max_length=10)),
                ("dia12", models.CharField(max_length=10)),
                ("dia13", models.CharField(max_length=10)),
                ("dia14", models.CharField(max_length=10)),
                ("dia15", models.CharField(max_length=10)),
                ("dia16", models.CharField(max_length=10)),
                ("dia17", models.CharField(max_length=10)),
                ("dia18", models.CharField(max_length=10)),
                ("dia19", models.CharField(max_length=10)),
                ("dia20", models.CharField(max_length=10)),
                ("dia21", models.CharField(max_length=10)),
                ("dia22", models.CharField(max_length=10)),
                ("dia23", models.CharField(max_length=10)),
                ("dia24", models.CharField(max_length=10)),
                ("dia25", models.CharField(max_length=10)),
                ("dia26", models.CharField(max_length=10)),
                ("dia27", models.CharField(max_length=10)),
                ("dia28", models.CharField(max_length=10)),
                ("dia29", models.CharField(max_length=10)),
                ("dia30", models.CharField(max_length=10)),
                ("dia31", models.CharField(max_length=10)),
                ("data_upload", models.DateTimeField()),
                ("setor", models.CharField(max_length=100)),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListaEmpregados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.IntegerField()),
                ("nome", models.CharField(max_length=200)),
                ("data_atualizacao", models.DateTimeField()),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
            options={"unique_together": {("matricula", "mes", "ano")},},
        ),
    ]
