# Generated by Django 4.2.2 on 2023-06-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planilhas", "0002_listaempregados_cargo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="listaempregados",
            unique_together={("matricula", "nome", "cargo", "mes", "ano")},
        ),
    ]
