# Generated by Django 4.2.2 on 2023-06-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planilhas", "0003_alter_listaempregados_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listaempregados",
            name="cargo",
            field=models.CharField(max_length=50),
        ),
    ]
