# Generated by Django 4.2.2 on 2023-06-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planilhas", "0004_alter_listaempregados_cargo"),
    ]

    operations = [
        migrations.RemoveField(model_name="planilhaconfirmacao", name="cargo",),
        migrations.RemoveField(model_name="planilhaconfirmacao", name="nome",),
        migrations.RemoveField(model_name="planilhasolicitacao", name="cargo",),
        migrations.RemoveField(model_name="planilhasolicitacao", name="nome",),
        migrations.AddField(
            model_name="planilhaconfirmacao",
            name="empregado",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="planilhas.listaempregados",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planilhasolicitacao",
            name="empregado",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="planilhas.listaempregados",
            ),
            preserve_default=False,
        ),
    ]
