# Generated by Django 4.2.2 on 2024-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planilhas", "0005_remove_planilhaconfirmacao_cargo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planilhaconfirmacao",
            name="setor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="planilhasolicitacao",
            name="setor",
            field=models.CharField(max_length=200),
        ),
    ]
