# Generated by Django 4.1.7 on 2023-04-28 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empregados", "0003_alter_empregado_mes_alter_importacoes_mes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioBatidasRejeitadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("entrada", models.TimeField()),
                ("saida", models.TimeField()),
                (
                    "data_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
    ]
