# Generated by Django 4.1.7 on 2023-04-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos_calculo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatoriobatidasrejeitadas", name="entrada",
        ),
        migrations.RemoveField(model_name="relatoriobatidasrejeitadas", name="saida",),
    ]
