# Generated by Django 4.1.7 on 2023-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_calculo", "0002_remove_relatoriobatidasrejeitadas_entrada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriobatidasrejeitadas",
            name="data",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
