# Generated by Django 4.1.7 on 2023-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_calculo", "0003_relatoriobatidasrejeitadas_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriobatidasrejeitadas",
            name="batida",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
