# Generated by Django 4.1.7 on 2023-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_calculo", "0004_relatoriobatidasrejeitadas_batida"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatoriobatidasrejeitadas",
            name="tipo",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
