# Generated by Django 4.1.7 on 2023-05-05 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0004_alter_cargahoraria_nome_alter_empregado_nome"),
        ("pos_calculo", "0006_relatoriobancosrecalculados"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioRubricasLancadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("rubrica", models.CharField(max_length=10)),
                ("valor", models.CharField(max_length=50)),
                (
                    "data_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
    ]
