# Generated by Django 4.1.7 on 2023-06-01 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0005_alter_cargahoraria_nome_alter_empregado_nome"),
        ("pos_calculo", "0008_alter_relatoriobancosrecalculados_nome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioBatidasDesrejeitadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data", models.CharField(max_length=30)),
                ("batida", models.IntegerField()),
                ("tipo", models.CharField(max_length=30)),
                (
                    "data_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
    ]
