# Generated by Django 4.2.2 on 2024-01-30 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("empregados", "0005_alter_cargahoraria_nome_alter_empregado_nome"),
        ("pos_calculo", "0010_relatorioescalavoltada"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioEscalaTirada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data", models.CharField(max_length=30)),
                ("escala", models.CharField(max_length=30)),
                (
                    "data_upload",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("importado_por", models.CharField(max_length=100)),
                ("importado_por_id", models.IntegerField()),
                (
                    "empregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.empregado",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empregados.importacoes",
                    ),
                ),
            ],
        ),
    ]
